repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.9
  hooks:
    # Run the linter.
    - id: ruff
      args: [--select, I, --fix]
    # Run the formatter.
    - id: ruff-format
      args: [--update]
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.34.0
  hooks:
    - id: djlint-reformat
      types_or: [html, jinja]
    - id: djlint
      types_or: [html, jinja]