version: "3.9"

services:
  app:
    build: .
    image: arbirich:latest
    container_name: arbirich_app
    ports:
      - "8080:8080"  # Expose your FastAPI application on port 8080
    environment:
      - REDIS_HOST=redis
      # Add any other environment variables your app needs.
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-arbirich
    ports:
      - "6379:6379"
