version: "3.9"

services:
  app:
    build: .
    image: arbirich:latest
    container_name: arbirich_app
    ports:
      - "8080:8080"  # Expose your FastAPI application on port 8080
    environment:
      - REDIS_HOST=redis
      - REDIS_DATABAS=0
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=arbidb
      - POSTGRES_USER=arbiuser
      - POSTGRES_PASSWORD=arbipassword
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    container_name: redis-arbirich
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_DATABASE=0

  postgres:
    image: postgres:latest
    container_name: postgres-arbirich
    environment:
      POSTGRES_DB: arbidb
      POSTGRES_USER: arbiuser
      POSTGRES_PASSWORD: arbipassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
