"""
Global constants for the ArbiRich application.
These constants are used throughout the application.
"""

from src.arbirich.models.enums import (
    ChannelName,
    LogLevel,
    OperationalConstants,
    RedisKeyPrefix,
    Status,
    TableName,
    TimeConstants,
)

# Redis channel names
TRADE_OPPORTUNITIES_CHANNEL = ChannelName.TRADE_OPPORTUNITIES.value
TRADE_EXECUTIONS_CHANNEL = ChannelName.TRADE_EXECUTIONS.value
ORDER_BOOK_CHANNEL = ChannelName.ORDER_BOOK.value
STATUS_UPDATES_CHANNEL = ChannelName.STATUS_UPDATES.value
OPPORTUNITY_CHANNEL = ChannelName.OPPORTUNITY.value
EXECUTION_CHANNEL = ChannelName.EXECUTION.value
STATS_CHANNEL = ChannelName.STATS.value
BROADCAST_CHANNEL = "broadcast"  # General channel for broadcasting messages

# Database table names
EXCHANGES_TABLE = TableName.EXCHANGES.value
TRADING_PAIRS_TABLE = TableName.TRADING_PAIRS.value
STRATEGIES_TABLE = TableName.STRATEGIES.value
TRADE_OPPORTUNITIES_TABLE = TableName.TRADE_OPPORTUNITIES.value
TRADE_EXECUTIONS_TABLE = TableName.TRADE_EXECUTIONS.value
STRATEGY_METRICS_TABLE = TableName.STRATEGY_METRICS.value
STRATEGY_TRADING_PAIR_METRICS_TABLE = TableName.STRATEGY_TRADING_PAIR_METRICS.value
STRATEGY_EXCHANGE_METRICS_TABLE = TableName.STRATEGY_EXCHANGE_METRICS.value
STRATEGY_TYPES_TABLE = TableName.STRATEGY_TYPES.value
RISK_PROFILES_TABLE = TableName.RISK_PROFILES.value
STRATEGY_PARAMETERS_TABLE = TableName.STRATEGY_PARAMETERS.value
STRATEGY_TYPE_PARAMETERS_TABLE = TableName.STRATEGY_TYPE_PARAMETERS.value
STRATEGY_EXCHANGE_PAIR_MAPPINGS_TABLE = TableName.STRATEGY_EXCHANGE_PAIR_MAPPINGS.value
STRATEGY_EXECUTION_MAPPING_TABLE = TableName.STRATEGY_EXECUTION_MAPPING.value
EXECUTION_STRATEGIES_TABLE = TableName.EXECUTION_STRATEGIES.value
SYSTEM_HEALTH_CHECKS_TABLE = TableName.SYSTEM_HEALTH_CHECKS.value

# Redis key prefixes
ORDER_BOOK_KEY_PREFIX = RedisKeyPrefix.ORDER_BOOK.value
TRADE_OPPORTUNITY_KEY_PREFIX = RedisKeyPrefix.TRADE_OPPORTUNITY.value
TRADE_EXECUTION_KEY_PREFIX = RedisKeyPrefix.TRADE_EXECUTION.value
DEDUP_KEY_PREFIX = RedisKeyPrefix.DEDUP.value
BALANCE_KEY_PREFIX = RedisKeyPrefix.BALANCE.value
SESSION_KEY_PREFIX = RedisKeyPrefix.SESSION.value
LOCK_KEY_PREFIX = RedisKeyPrefix.LOCK.value

# Time constants (in seconds)
OPPORTUNITY_TTL = TimeConstants.OPPORTUNITY_TTL
DEBOUNCE_TTL = TimeConstants.DEBOUNCE_TTL
HEALTH_CHECK_INTERVAL = TimeConstants.HEALTH_CHECK_INTERVAL
RECONNECT_DELAY = TimeConstants.RECONNECT_DELAY

# Operational constants
MAX_RETRY_ATTEMPTS = OperationalConstants.MAX_RETRY_ATTEMPTS
DEFAULT_BATCH_SIZE = OperationalConstants.DEFAULT_BATCH_SIZE
PRICE_PRECISION = OperationalConstants.PRICE_PRECISION
VOLUME_PRECISION = OperationalConstants.VOLUME_PRECISION
MIN_ORDER_SIZE = OperationalConstants.MIN_ORDER_SIZE
MAX_SLIPPAGE_PERCENT = OperationalConstants.MAX_SLIPPAGE_PERCENT
MAX_EXECUTION_RETRIES = OperationalConstants.MAX_EXECUTION_RETRIES
EXECUTION_TIMEOUT_MS = OperationalConstants.EXECUTION_TIMEOUT_MS

# Status constants
STATUS_ACTIVE = Status.ACTIVE.value
STATUS_INACTIVE = Status.INACTIVE.value
STATUS_ERROR = Status.ERROR.value
STATUS_PENDING = Status.PENDING.value
STATUS_WARNING = Status.WARNING.value
STATUS_COMPLETE = Status.COMPLETE.value

# Log levels as constants
LOG_DEBUG = LogLevel.DEBUG.value
LOG_INFO = LogLevel.INFO.value
LOG_WARNING = LogLevel.WARNING.value
LOG_ERROR = LogLevel.ERROR.value
LOG_CRITICAL = LogLevel.CRITICAL.value

# Define channels for WebSocket communication
WEBSOCKET_CHANNELS = [
    TRADE_OPPORTUNITIES_CHANNEL,
    TRADE_EXECUTIONS_CHANNEL,
    ORDER_BOOK_CHANNEL,
    STATUS_UPDATES_CHANNEL,
    BROADCAST_CHANNEL,
]

# Application constants
APP_NAME = "ArbiRich"
APP_VERSION = "0.2.0"
MAX_LOG_SIZE = 10 * 1024 * 1024  # 10 MB
MAX_LOG_BACKUPS = 5
LOG_ROTATION = "midnight"

# API rate limiting
API_RATE_LIMIT = 100  # requests per minute
API_RATE_LIMIT_WINDOW = 60  # seconds
